# Generated by Django 2.0.4 on 2018-04-27 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.World'),
        ),
    ]
